#!/usr/bin/env bash

declare -r profile="$AUTORANDR_CURRENT_PROFILE"

[[ -z "$profile" || ! "$profile" =~ (laptop|work) ]] && exit 1

killall --quiet --wait polybar

case "$profile" in
  laptop)
    MONITOR=eDP1 polybar top &
    ;;
  work)
    MONITOR=DP1 polybar top &
    MONITOR=eDP1 polybar top &
    ;;
esac

[[ -x "$HOME/.fehbg" ]] && "$HOME/.fehbg"
