#!/usr/bin/env bash

if [[ ! -d $HOME/.vim/bundle/Vundle.vim ]]; then
  git clone https://github.com/gmarik/Vundle.vim.git "$HOME/.vim/bundle/Vundle.vim"
  vim -u "$HOME/.vimrc.bundles" +PluginInstall +qall
  if [[ -d $HOME/.vim/bundle/YouCompleteMe ]]; then
    pushd "$HOME/.vim/bundle/YouCompleteMe" &> /dev/null
    ./install.py --clang-completer --gocode-completer
    popd &> /dev/null
  fi
fi
