#!/bin/bash

# Redirect output to stderr
exec 1>&2

REPO=$(basename $(git rev-parse --show-toplevel))
GEMFILE="Gemfile.lock"
VERSIONFILE="lib/$REPO/version.rb"

if [[ -f $GEMFILE && -f $VERSIONFILE ]]; then
  version=$(grep -oE "(\d+\.\d+\.\d+)" $VERSIONFILE)
  match=$(grep -qE "$REPO \($version[\w-]*\)" $GEMFILE)
  if [ $? -ne 0 ]; then
    echo -e "[ \033[0;31mpre-commit\033[0m ]: Version in $VERSIONFILE does not match version in $GEMFILE, do the \`bundle\`"
    exit 1
  fi
fi
