#!/usr/bin/env bash

set -e

# Redirect output to stderr
exec 1>&2

if [[ -z "$RC_SKIP_BREW" ]]; then
  if ! command -v brew &> /dev/null; then
    ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
  fi

  if command -v brew &> /dev/null; then
    brew update
    brew tap "homebrew/bundle"
    brew bundle check --file="$HOME/.dotfiles/host-sapphire/homebrew/Brewfile"
  fi
fi

if [[ -d $HOME/Dropbox/dotfiles/bin ]]; then
  for path in $HOME/Dropbox/dotfiles/bin/*; do
    dot_bin_path="$HOME/.bin/$(basename "$path")"
    [[ ! -e "$dot_bin_path" ]] && ln -s "$path" "$dot_bin_path"
  done
fi
