#!/usr/bin/env bash

readonly panel_height=24
readonly border_width=4
readonly window_gap=12
readonly split_ratio=0.5

bspc config bottom_padding $panel_height

bspc config normal_border_color   "#2E3440"
bspc config active_border_color   "#2E3440"
bspc config focused_border_color  "#81A1C1"
bspc config presel_feedback_color "#81A1C1"

bspc config border_width $border_width
bspc config window_gap   $window_gap
bspc config split_ratio  $split_ratio

bspc config pointer_follows_focus     true
bspc config pointer_follows_monitor   true
bspc config remove_disabled_monitors  true
bspc config remove_unplugged_monitors true

bspc config external_rules_command ~/.local/bin/bspwm-external-rules

bspc rule --add Slack   desktop=chat
bspc rule --add slack   desktop=chat

bspc rule --add Enpass                       state=floating center=on
bspc rule --add Blueman-manager              state=floating center=on
bspc rule --add xfce4-power-manager-settings state=floating center=on
bspc rule --add xfce4-settings-manager       state=floating center=on
bspc rule --add Pavucontrol                  state=floating center=on
bspc rule --add Seahorse                     state=floating center=on
