#!/usr/bin/env bash

readonly panel_height=24
readonly border_width=4
readonly window_gap=12
readonly split_ratio=0.5

bspc config bottom_padding $panel_height

bspc config normal_border_color   "#2E3440"
bspc config active_border_color   "#2E3440"
bspc config focused_border_color  "#81A1C1"
bspc config presel_feedback_color "#81A1C1"

bspc config border_width $border_width
bspc config window_gap   $window_gap
bspc config split_ratio  $split_ratio

# TODO: not available in version on Manjaro
# bspc config remomve_disabled_monitors  true
# bspc config remomve_unplugged_monitors true


bspc rule --add Slack   desktop=chat
bspc rule --add slack   desktop=chat
bspc rule --add Spotify desktop=music
bspc rule --add spotify desktop=music

bspc rule --add Enpass                       state=floating
bspc rule --add Blueman-manager              state=floating
bspc rule --add xfce4-power-manager-settings state=floating
bspc rule --add xfce4-settings-manager       state=floating
bspc rule --add Pavucontrol                  state=floating
