update

tap caskroom/cask
tap homebrew/binary
tap homebrew/dupes
tap homebrew/versions
tap thoughtbot/formulae

install rbenv
install ruby-build
install rbenv-builder
install rbenv-binstubs

install ack
install apple-gcc42
install jq
install ncdu
install parallel
install pv
install openssl
install openssh
install git
install tig
install curl
install wget
install lesspipe
install htop-osx
install geoip
install gnupg
install gnutls

install zsh
install zsh-completions

install python
install go
install node
install npm

install vim --override-system-vi
install macvim
install reattach-to-user-namespace --wrap-launchctl --wrap-pbcopy-and-pbpaste
install tmux

install awscli
install elb-tools
install ec2-api-tools

install mongodb24
pin mongodb24

install cassandra
pin cassandra

install rabbitmq30
pin rabbitmq30

install redis
pin redis

install zookeeper
pin zookeeper

install zeromq32 --universal
pin zeromq32

install elasticsearch
pin elasticsearch
