update

tap caskroom/cask
tap homebrew/dupes
tap homebrew/services
tap homebrew/versions
tap thoughtbot/formulae

install rbenv
install ruby-build
install rbenv-builder
install rbenv-binstubs

install ack
install jq
install ncdu
install parallel
install pv
install openssl
install openssh
install git --with-brewed-curl --with-brewed-openssl
install tig
install curl
install wget
install lesspipe
install htop-osx

install consul
install docker
install peco
install postgresql

install zsh
install zsh-completions
install istat-menus

install python
install go
install node
install npm
install ant

install macvim --with-python --with-override-system-vim
install reattach-to-user-namespace --with-wrap-launchctl --with-wrap-pbcopy-and-pbpaste
install tmux

install awscli
install ccm

install mongodb24
install rabbitmq30
install redis
install zookeeper
install kafka
install zeromq32 --universal
install elasticsearch
