#!/bin/bash

installed() {
  brew list "$@" > /dev/null 2>&1
}

install() {
  if ! installed "$@"; then
    brew install "$@"
  fi
}

pin() {
  brew pin "$@"
}

update() {
  brew update
}

tapped() {
  brew tap | grep -q "$@"
}

tap() {
  if ! tapped "$@"; then
    brew tap "$@"
  fi
}

linkapps() {
  brew linkapps
}

cleanup() {
  brew cleanup
}

cask() {
  brew cask "$@"
}

if [ $# -eq 1 ]; then
  source "$1"
fi
