#!/bin/sh

if [ command -v brew > /dev/null 2>&1 ]; then
  brew bundle $HOME/.dotfiles/Brewfile
  brew bundle $HOME/.dotfiles/Caskfile
fi

if [ ! -e $HOME/.vim/bundle/vundle ]; then
  git clone https://github.com/gmarik/Vundle.vim.git $HOME/.vim/bundle/vundle
  vim -u $HOME/.vimrc.bundles +PluginInstall +qa
fi

if [ ! -e $HOME/.oh-my-zsh ]; then
  curl -L http://install.ohmyz.sh | sh
fi

if [ ! -e  $HOME/Library/Application\ Support/Karabiner/private.xml ]; then
  ln -nfs $HOME/.dotfiles/karabiner/private.xml $HOME/Library/Application\ Support/Karabiner/private.xml
fi