#!/usr/bin/env bash

set -euo pipefail

readonly RC_DEBUG="${RC_DEBUG:-""}"

[[ -n $RC_DEBUG ]] && set -x

function installed() {
  local name="$1"
  pacman -Qi "$name" > /dev/null 2> /dev/null
}

function pkg() {
  local name="$1"
  echo -n "checking $name: "
  if installed "$name"; then
    echo "found"
  else
    echo "not found"
    sudo pacman -S "$name" --noconfirm
  fi
}

function aur() {
  local name="$1"
  echo -n "checking $name: "
  if installed "$name"; then
    echo "found"
  else
    echo "not found"
    yay --aur --nocleanmenu --nodiffmenu --noeditmenu -S "$name"
  fi
}

declare directories=(
  "$XDG_CONFIG_HOME"
  "$XDG_DATA_HOME"
  "$XDG_CACHE_HOME"
  "$DEV_HOME"
  "$DEV_BIN"
  "$DEV_SRC"
  "$DEV_PKG"
)

mkdir -p ${directories[@]}

if [[ -f ../packages/official.lst ]]; then
  echo "> installing official packages"

  for pkgname in $(grep -Ev '^#' ../packages/official.lst); do
    pkg "$pkgname"
  done
else
  echo "no official package list, skipping" >&2
fi

if [[ -f ../packages/aur.lst ]]; then
  echo "> installing AUR packages"

  for pkgname in $(grep -Ev '^#' ../packages/aur.lst); do
    aur "$pkgname"
  done
else
  echo "no AUR package list, skipping" >&2
fi
