#!/usr/bin/env bash

# redirect output to stderr
exec 1>&2

set -e

declare -r rcm_functions="$(realpath "$(dirname "$0")"/../rcm/functions)"

[[ -n $RC_DEBUG ]] && set -x
[[ -f $rcm_functions ]] && source "$rcm_functions"

if [[ -n $RCRC || -e ~/.rcrc ]]; then
  source "${RCRC:-~/.rcrc}"
  for tag in $TAGS; do
    run-hook "tag-$tag" "pre-up"
  done
  if [[ -n $HOSTNAME ]]; then
    run-hook "host-$HOSTNAME" "pre-up"
  fi
fi

mkdir -p "$DEV_HOME" "$DEV_BIN" "$DEV_SRC" "$DEV_PKG"
