#!/usr/bin/env bash

# redirect output to stderr
exec 1>&2

set -e

declare -r rcm_functions="$(realpath $(dirname $(realpath $0))/../rcm/functions)"

[[ -n "$RC_DEBUG" ]] && set -x
[[ -f "$rcm_functions" ]] && . "$rcm_functions"

mkdir -p "$DEV_HOME" "$DEV_BIN" "$DEV_SRC" "$DEV_PKG"

tag-hook-run "pre-up"
