#!/usr/bin/env bash

[[ -n "$RC_DEBUG" ]] && set -x

sudo -v || exit 1

systemctl --user daemon-reload
systemctl --user enable ssh-agent.service
systemctl --user enable mopidy.service
systemctl --user enable backup-home.timer

up_dir="$(readlink -f ../)"
while read -r f; do
  ff="$(printf "%s" "$f" | sed -e "s,$up_dir,,")"
  if diff "$f" "$ff"; then
    echo "$f and $ff are identical"
  else
    sudo cp -v "$f" "$ff"
  fi
done < <(find "$(readlink -f ../etc)" -type f)

sudo systemctl daemon-reload
sudo systemctl enable lightdm.service
sudo systemctl enable openvpn-sleep.service
sudo systemctl enable "suspend@$USER.service"

if ! groups | grep -q 'docker' &> /dev/null; then
  sudo gpasswd -a $(whoami) docker
  newgrp docker
fi
