alias chmox="chmod +x"
alias freq="awk '{f[\$0]++} END {for(w in f) printf \"%i\t%s\n\",f[w],w}'"
alias uniqs="awk '{if(f[\$0]++==0)print \$0}'"
alias be="bundle exec"
alias b="bundle"
alias t="tig"
alias ta="tig --all"
alias gst="git status"
alias bi="bundle install --path vendor/bundle --binstubs .bundle/bin"
alias s="sudo"
