#!/usr/bin/env bash

# shellcheck disable=SC2155
# declare -r dotfiles_dir="$(realpath "$(dirname "$0")"/../)"
declare -r dotfiles_dir="$HOME/.dotfiles"

function run-hook() {
  local what="$1" hook="$2"
  hook_file="$dotfiles_dir/$what/hooks/$hook"
  if [[ -x "$hook_file" ]]; then
    pushd "$(dirname "$hook_file")" &> /dev/null
    "./$(basename "$hook_file")"
    popd &> /dev/null
  fi
}
