#!/usr/bin/env bash

[[ -n "$RC_DEBUG" ]] && set -x

sudo -v || exit 1

declare -r build_dir="/tmp/aur"

function installed {
  local pkg_name=$1
  pacman -Qi "$pkg_name" > /dev/null
}

function pkg_group {
  local pkg_group=$1
  if comm -23 <(pacman -Sgq "$pkg_group") <(pacman -Qgq "$pkg_group"); then
    echo "package group '$pkg_group' already installed"
  else
    sudo pacman -S "$pkg_group" --noconfirm
  fi
}

function pkg {
  local pkg_name=$1
  if installed "$pkg_name"; then
    echo "package '$pkg_name' already installed"
  else
    sudo pacman -S "$pkg_name" --noconfirm
  fi
}

function aur {
  local pkg_name=$1
  if installed "$pkg_name"; then
    echo "package '$pkg_name' already installed"
  else
    if command -v packer &> /dev/null; then
      packer -S "$pkg_name" --noconfirm --noedit
    else
      local pkg_dir="$build_dir/$pkg_name"
      mkdir -p "$pkg_dir"
      pushd "$pkg_dir"
      git clone "https://aur.archlinux.org/$pkg_name.git"
      makepkg -si
      popd
      rm -rf "$pkg_dir"
    fi
  fi
}
